import { translateKey } from '@/lib/i18n';
import type { AppLocale } from '@/lib/i18n';
import type { PublicAvailability } from '@/types';

/** Translates status codes, not server-generated presentation labels. */
const availabilityKeys = {
    available: 'public.common.available',
    limited: 'public.common.limited',
    in_transit: 'public.common.inTransit',
    unavailable: 'public.common.unavailable',
} as const;

export function publicAvailabilityLabel(
    status: PublicAvailability['status'],
    locale: AppLocale,
): string {
    return translateKey(availabilityKeys[status], locale);
}

/**
 * The seeded branch hero uses Indonesian copy even for English visitors.
 * Localize that exact system default, but never rewrite operator-authored text.
 * Per-language operator copy requires a separate content-management feature.
 */
export function publicHomeText(
    stored: string | null | undefined,
    key: 'public.home.fallbackHero' | 'public.home.fallbackDescription',
    locale: AppLocale,
    fallback = translateKey(key, locale),
): string {
    const value = stored?.trim();

    if (!value || value === translateKey(key, 'id')) {
        return fallback;
    }

    return stored ?? value;
}

/** Only translates the standardized duration labels generated by the PHP rate mapper. */
export function publicRateDurationLabel(
    label: string,
    locale: AppLocale,
): string {
    const match = /^(\d+)\s+(menit|jam|hari|minggu|bulan)$/i.exec(label.trim());

    if (!match) {
        return label;
    }

    const count = Number(match[1]);
    const unit = match[2].toLowerCase();
    const englishUnits: Record<string, [string, string]> = {
        menit: ['minute', 'minutes'],
        jam: ['hour', 'hours'],
        hari: ['day', 'days'],
        minggu: ['week', 'weeks'],
        bulan: ['month', 'months'],
    };

    if (locale === 'id') {
        return `${new Intl.NumberFormat('id-ID').format(count)} ${unit}`;
    }

    const english = englishUnits[unit];

    return `${new Intl.NumberFormat('en-US').format(count)} ${count === 1 ? english[0] : english[1]}`;
}

/** Public API period durations are numeric; render them independently of server locale. */
export function publicDurationMinutesLabel(
    minutes: number,
    locale: AppLocale,
): string {
    const whole = Math.max(0, Math.floor(minutes));
    const hours = Math.floor(whole / 60);
    const remainder = whole % 60;

    if (locale === 'en') {
        const hourText = hours
            ? `${hours} ${hours === 1 ? 'hour' : 'hours'}`
            : '';
        const minuteText = remainder
            ? `${remainder} ${remainder === 1 ? 'minute' : 'minutes'}`
            : '';

        return [hourText, minuteText].filter(Boolean).join(' ') || '0 minutes';
    }

    return (
        [hours ? `${hours} jam` : '', remainder ? `${remainder} menit` : '']
            .filter(Boolean)
            .join(' ') || '0 menit'
    );
}
